package docs

import (
	"os"
	"regexp"
	"strings"
	"testing"
)

// TestLLMsTxt_MatchesCatalog verifies that the on-disk llms.txt at the
// repository root matches the content generated by GenerateLLMsTxt().
// This test fails the build when llms.txt has drifted from the generator
// (CR-0061 FR-15).
func TestLLMsTxt_MatchesCatalog(t *testing.T) {
	// Traverse up from internal/docs to the repository root.
	onDisk, err := os.ReadFile("../../llms.txt")
	if err != nil {
		t.Fatalf("failed to read llms.txt: %v (run 'make docs-bundle' to regenerate)", err)
	}

	generated := GenerateLLMsTxt()
	if string(onDisk) != generated {
		t.Errorf("llms.txt is stale; run 'make docs-bundle' to regenerate.\n\nExpected:\n%s\n\nGot on disk:\n%s", generated, string(onDisk))
	}
}

// TestLLMsTxt_StructureCompliesWithStandard verifies that the generated
// llms.txt begins with a single H1, contains a blockquote summary, and
// has H2 sections with list items formatted as "[title](url): description"
// (CR-0061 AC-9).
func TestLLMsTxt_StructureCompliesWithStandard(t *testing.T) {
	text := GenerateLLMsTxt()
	lines := strings.Split(text, "\n")

	if len(lines) == 0 {
		t.Fatal("GenerateLLMsTxt returned empty string")
	}

	// Must start with a single H1.
	if !strings.HasPrefix(lines[0], "# ") {
		t.Errorf("first line must be an H1, got: %q", lines[0])
	}

	// Must contain a blockquote summary line.
	hasBlockquote := false
	for _, l := range lines {
		if strings.HasPrefix(l, "> ") {
			hasBlockquote = true
			break
		}
	}
	if !hasBlockquote {
		t.Error("llms.txt must contain a blockquote summary line starting with '> '")
	}

	// Must contain required H2 sections.
	requiredH2 := []string{"## Docs", "## Tools", "## Change Requests", "## Optional"}
	for _, h2 := range requiredH2 {
		if !strings.Contains(text, h2+"\n") {
			t.Errorf("llms.txt missing required H2 section %q", h2)
		}
	}

	// List items must follow "[title](url): description" format.
	itemPattern := regexp.MustCompile(`^\- \[.+\]\(https://.+\): .+$`)
	for i, l := range lines {
		if strings.HasPrefix(l, "- [") {
			if !itemPattern.MatchString(l) {
				t.Errorf("line %d does not match item format '[title](url): description': %q", i+1, l)
			}
		}
	}
}

// TestLLMsTxt_LinksAreAbsolute verifies that every URL in the generated
// llms.txt is an absolute GitHub URL on the main branch, with no relative
// paths (CR-0061 FR-14).
func TestLLMsTxt_LinksAreAbsolute(t *testing.T) {
	text := GenerateLLMsTxt()

	// Extract all markdown link URLs: [text](url)
	linkPattern := regexp.MustCompile(`\]\(([^)]+)\)`)
	matches := linkPattern.FindAllStringSubmatch(text, -1)

	if len(matches) == 0 {
		t.Error("no links found in generated llms.txt")
	}

	for _, m := range matches {
		url := m[1]
		if !strings.HasPrefix(url, "https://github.com/desek/outlook-local-mcp/") {
			t.Errorf("link URL is not an absolute GitHub URL: %q", url)
		}
		if strings.Contains(url, "..") || (!strings.Contains(url, "/blob/") && !strings.Contains(url, "/tree/") && !strings.HasSuffix(url, "/")) {
			t.Errorf("link URL does not reference blob or tree on a branch: %q", url)
		}
	}
}
